name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -e .
    - name: flake8
      run: |
        config/hooks/pre-commit
    - name: Test with pytest
      run: |
        pytest
    - name: end2end
      run: |
        ./tests/end2end/run_exp1.sh
